import { isAbsolute, normalize, sep } from 'node:path'
import type { AppConfig, ManagedApplication, ProxyProfile } from '../shared/types'
import { normalizeDomain } from '../shared/domain-rules'

export { normalizeDomain } from '../shared/domain-rules'

const HOST_PATTERN = /^(?:\[[0-9a-fA-F:]+\]|[0-9a-zA-Z._:-]+)$/

export function validateConfig(config: AppConfig): AppConfig {
  if (config.version !== 4) throw new Error('不支持的配置版本')
  const networkServices = [...new Set(config.networkServices.map((service) => service.trim()).filter(Boolean))]
  if (networkServices.length === 0) throw new Error('请至少选择一个系统网络入口')
  if (!Number.isInteger(config.pacPort) || config.pacPort < 1024 || config.pacPort > 65535) {
    throw new Error('PAC 端口必须在 1024–65535 之间')
  }
  if (!Number.isInteger(config.relayPort) || config.relayPort < 1024 || config.relayPort > 65535) {
    throw new Error('流量转发端口必须在 1024–65535 之间')
  }
  if (config.relayPort === config.pacPort) throw new Error('PAC 端口与流量转发端口不能相同')

  const proxyIds = new Set<string>()
  const proxies = config.proxies.map((proxy) => validateProxy(proxy, proxyIds))
  const loopbackNames = new Set(['127.0.0.1', '::1', '[::1]', 'localhost'])
  const loopbackProxy = proxies.find(
    (proxy) => loopbackNames.has(proxy.host.toLowerCase()) && proxy.port === config.relayPort
  )
  if (loopbackProxy) throw new Error(`代理 ${loopbackProxy.name} 与本地流量转发端口相同，会形成循环连接`)
  const ruleIds = new Set<string>()
  const domains = new Set<string>()
  const rules = config.rules.map((rule) => {
    if (!rule.id || ruleIds.has(rule.id)) throw new Error('域名规则 ID 无效或重复')
    ruleIds.add(rule.id)
    const domain = normalizeDomain(rule.domain)
    if (!domain) throw new Error(`域名格式无效：${rule.domain || '(空)'}`)
    if (domains.has(domain)) throw new Error(`域名重复：${domain}`)
    domains.add(domain)
    if (!proxyIds.has(rule.proxyId)) throw new Error(`域名 ${domain} 引用了不存在的代理`)
    return { ...rule, domain, enabled: Boolean(rule.enabled), matchSubdomains: Boolean(rule.matchSubdomains) }
  })

  const applicationIds = new Set<string>()
  const applicationPaths = new Set<string>()
  const applications = (config.applications ?? []).map((application) =>
    validateApplication(application, applicationIds, applicationPaths)
  )

  return {
    version: 4,
    networkServices,
    pacPort: config.pacPort,
    relayPort: config.relayPort,
    proxies,
    rules,
    applications
  }
}

function validateApplication(
  application: ManagedApplication,
  ids: Set<string>,
  paths: Set<string>
): ManagedApplication {
  if (!application.id || ids.has(application.id)) throw new Error('应用 ID 无效或重复')
  ids.add(application.id)
  const name = application.name.trim()
  const path = normalize(application.path.trim())
  const executablePath = normalize(application.executablePath.trim())
  if (!name) throw new Error('应用名称不能为空')
  if (!isAbsolute(path) || !path.toLowerCase().endsWith('.app')) throw new Error(`应用路径无效：${path || '(空)'}`)
  if (paths.has(path)) throw new Error(`应用重复：${name}`)
  paths.add(path)
  const executableRoot = `${path}${sep}Contents${sep}MacOS${sep}`
  if (!isAbsolute(executablePath) || !executablePath.startsWith(executableRoot)) {
    throw new Error(`应用可执行文件路径无效：${name}`)
  }
  return {
    ...application,
    name,
    path,
    executablePath,
    bundleId: application.bundleId?.trim() || null
  }
}

function validateProxy(proxy: ProxyProfile, ids: Set<string>): ProxyProfile {
  if (!proxy.id || ids.has(proxy.id)) throw new Error('代理 ID 无效或重复')
  ids.add(proxy.id)
  const name = proxy.name.trim()
  const host = proxy.host.trim()
  if (!name) throw new Error('代理名称不能为空')
  if (!HOST_PATTERN.test(host) || host.includes('://')) throw new Error(`代理地址无效：${host || '(空)'}`)
  if (!Number.isInteger(proxy.port) || proxy.port < 1 || proxy.port > 65535) {
    throw new Error(`代理 ${name} 的端口无效`)
  }
  if (!['HTTP', 'HTTPS', 'SOCKS5'].includes(proxy.protocol)) throw new Error(`代理 ${name} 的协议无效`)
  return { ...proxy, name, host, port: proxy.port }
}

export function generatePac(configInput: AppConfig): string {
  const config = validateConfig(configInput)
  const rules = config.rules
    .filter((rule) => rule.enabled)
    .map((rule) => ({
      domain: rule.domain,
      matchSubdomains: rule.matchSubdomains,
      endpoint: `PROXY 127.0.0.1:${config.relayPort}`
    }))

  return `// Generated by Domain Relay. Matched traffic enters the local metered relay first.
function FindProxyForURL(url, host) {
  host = host.toLowerCase();
  var rules = ${JSON.stringify(rules)};

  for (var i = 0; i < rules.length; i++) {
    var rule = rules[i];
    if (host === rule.domain || (rule.matchSubdomains && dnsDomainIs(host, "." + rule.domain))) {
      return rule.endpoint;
    }
  }

  return "DIRECT";
}
`
}
